os: osx
language: generic
before_install:
  - brew install terraform
  - brew install aliyun-cli
deploy:
  provider: script
  script: sh scripts/deploy.sh
  on:
    branch: master
after_deploy: sh scripts/clean.sh